// default package
// Generated Oct 31, 2017 11:36:24 AM by Hibernate Tools 5.1.5.Final
package vn.ifisolution.fresher12.entity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblProject generated by hbm2java
 */
@Entity
@Table(name = "tblProject_khoa")
public class TblProject implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date startDate;
	private Date endDate;
	private String description;
	private Set<TblTimeSheets> tblTimeSheetses = new HashSet<TblTimeSheets>(0);

	public TblProject() {
	}

	public TblProject(String name, String description, Date startDate, Date endDate) {
		this.name = name;
		this.description = description;
		this.endDate = endDate;
		this.startDate = startDate;
	}
	
	public TblProject(String name, String description, Set<TblTimeSheets> tblTimeSheetses) {
		this.name = name;
		this.description = description;
		this.tblTimeSheetses = tblTimeSheetses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblProject")
	public Set<TblTimeSheets> getTblTimeSheetses() {
		return this.tblTimeSheetses;
	}

	public void setTblTimeSheetses(Set<TblTimeSheets> tblTimeSheetses) {
		this.tblTimeSheetses = tblTimeSheetses;
	}

}

