// default package
// Generated Oct 31, 2017 11:36:24 AM by Hibernate Tools 5.1.5.Final
package vn.ifisolution.fresher12.entity;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTimeSheets generated by hbm2java
 */
@Entity
@Table(name = "tblTimeSheets_khoa")
public class TblTimeSheets implements java.io.Serializable {

	private Integer id;
	private TblPersional tblPersional;
	private TblProject tblProject;
	private Date startDate;
	private Date endDate;
	private String description;
	private String type;

	public TblTimeSheets() {
	}

	public TblTimeSheets(TblPersional tblPersional, TblProject tblProject, java.sql.Date startDate, java.sql.Date endDate, String description, String type) {
		this.tblPersional = tblPersional;
		this.tblProject = tblProject;
		this.startDate = startDate;
		this.endDate = endDate;
		this.type = type;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersonal", nullable = false)
	public TblPersional getTblPersional() {
		return this.tblPersional;
	}

	public void setTblPersional(TblPersional tblPersional) {
		this.tblPersional = tblPersional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProject", nullable = false)
	public TblProject getTblProject() {
		return this.tblProject;
	}

	public void setTblProject(TblProject tblProject) {
		this.tblProject = tblProject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	@Column(name = "description", nullable = false, length = 255)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name = "type", nullable = false, length = 40)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	

}
