---
server:
  port: 8080
  contextPath: /Asignment5_Fresher12
---
spring:
  profiles: local, default
  data:
    cassandra:
      keyspace-name: asignment5
      contact-points: 127.0.0.1
      port: 9042